site_name: ClonMapper
site_url: https://docs.brocklab.com/clonmapper

hooks:
  - hooks.py

nav:
  - Home: "index.md"
  - Full Protocol: "full-protocol.md" 
  - Protocol by Section:
    - "protocol/introduction.md"
    - "protocol/materials.md"
    - "protocol/methods.md"
    - "protocol/html-tables.md"
    - "protocol/acknowledgements.md"
  - PDF: "pdf/index.md"
  - Sequences: "sequences/index.md"
  - Resources: "resources.md"
  - Citation: "citation.md"

theme:
  name: material
  custom_dir: .overrides
  favicon: assets/favicon.png

  static_templates:
  - pdf/latest/index.html

  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - toc.follow
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - bibtex:
      bib_file: "../bib/protocol.bib"
      footnote_format: "ref{number}"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - tables
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true

